### ISSUE TITLE
I need to know when to run haskell-updater

### ISSUE THREAD

**Issue by mpkh** [gentoo-haskell/haskell-updater#7]
It's important to have anything automatic without user actions.
- I want to know that there will be error w/o running haskell-updater or not
- I need to know if after running haskell-updater I need to run it second time

Is it possible? Alternative way (sounds less robust for me) is some wrapper catching portage error message telling stuff about haskell-updater and running it by that case.

What will you suggest there? /cc @trofi @qnikst

**Comment by hasufell** [comment]
> It's important to have anything automatic without user actions.

Haskell ABI is non-trivially broken. I don't think there is a reasonable way to always catch a possible ABI breakage, not even with slots/subslots.

**Comment by Heather** [comment]
@hasufell using haskell packages on Gentoo I need to run `haskell-updater` really often and honestly when I'm updating system and it breaks just because I neede to run it two times somewhere between webktit-gtk and chromium I'm losing real time and it sounds like a reason for me to fight with those perioudical breaks

**Comment by hasufell** [comment]
So fix ABI support in GHC, lol.

**Comment by Heather** [comment]
@hasufell nah it's lame, I'd better write own compiler but for now I need semihow faster solution

**Comment by qnikst** [comment]
Any update will require running haskell-updater for all it's reverse-deps (as simple as that). We thought about some notification, but I'm not sure if there were a sane solution that will not require log parsing.

**Comment by hasufell** [comment]
Theoretically, haskell-updater functionality could be integrated into the package managers `revdep-rebuild` (on portage) and `cave fix-linkage` (on paludis). But that'll rather become a problem, so having it as a separate tool makes actually sense.

**Comment by trofi** [comment]
the practical part
=============

You need to run haskell-updater every time when 'haskell-updater -q -l' reports something.
But it does not guard you against bugs in ebuilds which never get fixed by 'haskell-updater'
run.

I personally run upgrades on my systems nightly and run haskell-updater twice. My script looks like:
```
    emerge -vuDN @world --jobs="$(($(nproc) + 1))" --verbose-conflicts --backtrack=100 \
        --keep-going --with-bdeps=y --complete-graph
    haskell-updater -- --jobs="$(($(nproc) + 1))" --verbose-conflicts --backtrack=100
    haskell-updater -- --jobs="$(($(nproc) + 1))" --verbose-conflicts --backtrack=100
    emerge @preserved-rebuild --keep-going --jobs="$(($(nproc) + 1))" --verbose-conflicts
```
It's not ideal but it's good-enough for me to get working system every morning.
Usually even a single 'haskell-updater' run is enough to fix package breakages.

the theoretical part
===============

Haskell programs and libraries extensively reuse entitites (types,
functions, rewrite rules, type instances, other stuff) exported from
external libraries as non-opaque entities to allow aggressive cross-module
inlining to compile away deep layers of abstraction. It's language's feature.

I personally don't see it as a broken idea. No more broken that allowing
LTO across library boundaries or using 'static inline' C functions or
#define macros in C headers.

If you accept the fact transitive dependencies being able to
break ABI is not a GHC bug (and not a haskell-specific thing)
and an occasionally useful thing then you might agree the
problem needs to be fixed somewhere else.

In haskell's case the package manager seems to be a natural choice
because we can consistently mark our packages as potentially
breaking all the revdeps and those need to be rebuilt. We already know it.

portage added SUBSLOT rebuilds for exactly the same
unstable ABI problem as a main user: to rebuild revdeps
of a package if upgrade changes package's ABI.
It has on elimitation: you can't express SUBSLOT relation
deeper in hierarchy.

Portage feature request: https://bugs.gentoo.org/show_bug.cgi?id=449094
gentoo-haskell overlay bug: https://github.com/gentoo-haskell/gentoo-haskell/issues/199

**Comment by Heather** [comment]
@trofi the fact that you're running it twice is a bit horrible... I mean it's how users must use it I guess, run two timesm which is maybe teaching for beginners of Why and How... but still not very common in practical

**Comment by hasufell** [comment]
@Heather the situation will not improve as haskellers usually don't care or think of it as a feature. If you say it's broken for most distros they point you to NixOS or stack. I'm actually of the opinion that it would be better to drop  90% of all haskell packages and just ship the main haskell platform. The user can deal with the rest, which is barely maintainable on PM level.

**Comment by hasufell** [comment]
> No more broken that allowing
> LTO across library boundaries

difference being that LTO is optional and known to be highly experimental

**Comment by qnikst** [comment]
Yes, while Haskell approach is optional and stable.

**Comment by hasufell** [comment]
> Yes, while Haskell approach is optional^W^W and stable.

Uh. So dynamic linking actually works and ABI is not broken when you compile the same thing twice?

**Comment by qnikst** [comment]
I don't know why you compile *same* thing twice, I bet you compile different things because there are different interface and object files.

**Comment by hasufell** [comment]
> I don't know why you compile same thing twice, I bet you compile different things because there are different interface and object files.

No.

I don't even know what you are arguing about. ABI is broken in haskell/GHC and there is no way you can have the same behavior as in a language like C. You cannot opt out from it. period.

**Comment by qnikst** [comment]
> No.

No, you *are* compiling *different* programs, if update of the library doesn't change interface, then it's guaranteed that you don't need to rebuild anything. 

Please define "broken" before going into discussion any further, haskell ABI works as intended, so it's not definitely *not broken*.  Sorry, I don't get why haskell should have behaviour from the 70th..

**Comment by hasufell** [comment]
> No, you are compiling different programs, if update of the library doesn't change interface, then it's guaranteed that you don't need to rebuild anything.

That's not what they told me at `#haskell`. They said compiler temporaries can leak into the binary.

**Comment by Heather** [comment]
> If you say it's broken for most distros they point you to NixOS or stack

Yes, haskellers are terrible people, that's a known fact... 

But I still have a hope to have some sane solution there

**Comment by qnikst** [comment]
The interface file is the way how parts of the library can affect other libraries, if you have same interface file it's guaranteed that other libs will not be affected.

**Comment by qnikst** [comment]
Sane solution is to implement recursive subslots, I personally don't want to give up on 30+ years  of progress in compilers for the sake of the package manager simplicity :)

**Comment by Heather** [comment]
> That's not what they told me at `#haskell`.

My favorite thing was: "Do you even know what is induction"

**Comment by hasufell** [comment]
> I personally don't want to give up on 30+ years of progress in compilers for the sake of the package manager simplicity :)

You are assuming that those ideas are strictly incompatible. Yes, it will have a huge impact on optimization. So? If you need that extra bit of optimization, you could still do it, just not on system level.

**Comment by qnikst** [comment]
Sorry I can't do any interesting optimizations without cross package connections. Also I don't see what do you mean about system level, cross library inlining and rules, where are the system here? Or that you can't use package `a` that depends on `b-interface1` when you have `b-interface2` in the system to build anything?

**Comment by hasufell** [comment]
> Sorry I can't do any interesting optimizations without cross package connections.

I don't think optimization is number one concern if you install something system-wide.

> Also I don't see what do you mean about system level

Installing something system-wide.

**Comment by trofi** [comment]
> I'm actually of the opinion that it would be better to drop 90% of all haskell packages and just ship the main haskell platform

Then users would have to solve problems already solved by package manager for them.

Some people just want to try pandoc, git-annex, agda or darcs. It's a bit harsh to drag them
through hoops of figuring out all the non-haskell dependencies of these. And have them updated.

Some users just want profiling enabled for a couple of haskell libraries
or try out new fancy optimization flag on a single package.

Or share a fix for a commonly used package (like xmonad) with slow to respond upstream.

Or do something gentoo specific like enhancing support for hardened

> difference being that LTO is optional and known to be highly experimental

ABI hashes appeared in GHC around 6.12.  you can edit `*.conf` files in
`/usr/lib/ghc-7.10.3/package.conf.d/` and adjust `id:` and `key:` fields
to whatever value you count as an ABI change. See `-package-key`
and `-this-package-key` ghc options for more details.

The burden of maintaining and tracking ABI will be on you. If symbols match
then linker will happily produce you desired results. But you need to know what actually
affects real ABI (exported inlines, exported datatype layout changes, modules
names, strictness annotations, unpack pragmas), just like in C or C++.
`ghc --show-iface` can help in tracking ABI drift.

> So dynamic linking actually works

It doesn't for you? Dynamic linking is a default in gentoo starting from ghc-7.10.

> That's not what they told me at #haskell. They said compiler temporaries can leak into the binary.

They don't leak in an interface file and do not affect ABI hash.
GHC computes ABI hash before emitting assembly code (and object file) generation.

Debian wanted to get rid of bit drift in object files and fixed it: https://git.haskell.org/ghc.git/commitdiff/7a82b77691fb90c4af6863673f10e454a449739e

> and ABI is not broken when you compile the same thing twice?

If you get different results it's a compiler bug (and should be reported)
or you are generating different final code from template haskell.

Debian is concerned about byte-for-byte reproducible builds and about
package ABI hash stability as after minor patching as they need to rebuild
`.deb` packages as new versions.

Fixing this stuff is a long-running (and quite successful) effort:
    https://ghc.haskell.org/trac/ghc/ticket/4012

> I don't think optimization is number one concern if you install something system-wide.

Correctness is a nice-to-have feature though. Package run against the interface it was typechecked.

**Comment by hasufell** [comment]
> Then users would have to solve problems already solved by package manager for them.

Well, whenever I try to install haskell stuff (including darcs and pandoc which I both use) via the system, it gets me in way more trouble than using the user-wide cabal db. So not really agreeing there. Our PMs were built around C-like libraries and haskell barely meets any of those requirements. Adding all that complexity like subslots has in my opinion not improved usability that much. I think the only two real solutions are:
1. get more stable ABIs in haskell (that also includes less random API breakage in the library ecosystem)
2. fix the PM by rewriting it (which has already been done in Nix)... and not just the PM, also the spec

Both are impossible in gentoo, so dropping the majority of packages might actually decrease pain for the end-user.

> The burden of maintaining and tracking ABI will be on you. If symbols match
> then linker will happily produce you desired results. But you need to know what actually
> affects real ABI (exported inlines, exported datatype layout changes, modules
> names, strictness annotations, unpack pragmas), just like in C or C++.
> ghc --show-iface can help in tracking ABI drift.

I guess we can at least agree that ABI is extremely unstable because of that.

And we didn't even talk about the upper-version-bound hell that makes the depgraph so overcomplicated.

**Comment by qnikst** [comment]
> Well, whenever I try to install haskell stuff (including darcs and pandoc which I both use) via the system, it gets me in way more trouble than using the user-wide cabal db.

Do you have a way to update pandoc if it or it's deps  have changed? Can you easily update all packages which dependencies were broken? Can you fetch and see if you need to update your package or it's deps? Can you control system deps? Can you easily control per-packages and per-packages ghc flags? Hint: "No" to all of the questions.  Just because it's a package manager job, and either cabal-install, nor cabal-with-nixlike-env, nor stack are package managers in any sense. 

> Our PMs were built around C-like libraries and haskell barely meets any of those requirements. 

But it means, that we have a broken PM and we need to change that.

> Adding all that complexity like subslots has in my opinion not improved usability that much.

Yes, because for haskell subslots should be recursive. And algorithm for it's solving subslots deps should not be broken (and this time it's really broken because subslots should not be a part of backtracking, at least in a way that it's done now).

> I think the only two real solutions are:

3. make PM do it's job well?

> Both are impossible in gentoo, so dropping the majority of packages might actually decrease pain for the end-user.

I suppose that we should drop many outdated package version from tree, it will make portage much more happy. Currently in a portage there are only executables, it's deps and platform, I'd be happy to drop platform as well.

//Though I'm taking a very small portion of my time in gentoo maintenance so my voice should not be count here

**Comment by hasufell** [comment]
> Do you have a way to update pandoc if it or it's deps have changed?

Well, you can also run it in docker. The image rebuild is triggered automatically. That's how I deploy darcsden too. It's less nice though for cli stuff like pandoc/darcs, but some people do that.

Sure, it would be nicer to have the system handle it. I know the benefits that brings.

> But it means, that we have a broken PM and we need to change that.

That would involve starting from scratch, really. And it's not just the PM, it's the spec too. Adding portage-only hacks will make things break for a lot of other users.

> Yes, because for haskell subslots should be recursive. And algorithm for it's solving subslots deps should not be broken (and this time it's really broken because subslots should not be a part of backtracking, at least in a way that it's done now).

PM authors are not even agreeing that subslots were a good idea and that there is a reliable way to meet the following: ["The sub-slot is used to represent cases in which an upgrade to a new version of a package with a different sub-slot may require dependent packages to be rebuilt."](https://dev.gentoo.org/~ulm/pms/head/pms.html#x1-670007.2)
But if you ask only portage developers you will probably get an "ack" on everything. The implications of making this recursive are even less clear.

> make PM do it's job well?

Well yes, but unless it does it's job well, it shouldn't do anything. But that's just my opinion. You see, that's the reason someone opened this ticket, because things don't really work as expected and the solution is probably still far away.

So I guess @Heather either modify your update workflow or simply use cabal directly. It's on you how to figure out which is easier. I made my decision already.

**Comment by trofi** [comment]
> It's other problems that make haskell exceptionally hard to package that need to be fixed.

:)

**Comment by Heather** [comment]
maybe we should have @hasufell 's workflow somewhere in wiki

**Comment by hasufell** [comment]
> :)

?


> maybe we should have @hasufell 's workflow/reasoning somewhere in wiki

https://www.haskell.org/cabal/users-guide/

**Comment by trofi** [comment]
> > > It's other problems that make haskell exceptionally hard to package that need to be fixed.

> > :)

> ?

Existence of haskell overlay shows packaging is not hard at all.

Amount and structure of metadata for typical packages allows
ebuild generation which just works.

**Comment by hasufell** [comment]
> Amount and structure of metadata for typical packages allows
> ebuild generation which just works.

No, it doesn't. It has caused a lot of problems especially wrt malformed `|| ( ( >=dev-haskell/hashable-1.1.2.3 <dev-haskell/hashable-1.2 ) ( >=dev-haskell/hashable-1.2.1.0 <dev-haskell/hashable-1.3 ) )` deps. And that depstring is even redundant, since we didn't ship the "broken" `1.2.0.x` version which the depstring is trying to work around. Besides the fact that it's wrong anyway since the best choice must go first.

You cannot translate cabal deps to proper PMS deps, because semantics are not 100% the same. 

Automatically generated input is not necessarily of high quality.

**Comment by trofi** [comment]
1. Typical ebuilds certainly Just Work. If they don't in your opinion then there is noting left to discuss here.

2. The "hashable" depstring is not malformed.
3. The only "a lot of problems" is to pick older version which is not a problem in itself.
4. To get a working system you don't need the "100% the same". You gave a relaxing example  2 sentenced before.

**Comment by qnikst** [comment]
@hasufell if you want to have constructive discussion, please be more concrete and not hesitate to explain properly when you use "mailformed", "broken" and other crappy terms. Otherwise discussion can't be constructive at all and lead to any benefit neither for the repo or distro, or for the mental health of the participants.
For example, can you quote or give a link to PMS that shows that string is malformed, if it's a case, then we should fill a bug for `hackport` (as it generates wrong lines) and `repoman` of cause (because repoman should show a error if there is a mailformed strings in ebuild). If you relate to something as broken, please, don't hesitate to explain exactly is broken as you think, and "it doesn't work like a subset of C" is not an explanation.

**Comment by hasufell** [comment]
@trofi 

> Typical ebuilds certainly Just Work. If they don't in your opinion then there is noting left to discuss here.

That's a bit optimistic. You don't expect me to harvest bugzilla now, do you? :)

My point is that just relying on hackport is not enough. So we can improve the input. And that's often not so easy, since cabal definitions are sometimes incorrect with overly strict upper version bounds.

> The "hashable" depstring is not malformed.

Ok, what's the purpose then if the `1.2.0.x` version does not exist?


@qnikst 

> For example, can you quote or give a link to PMS that shows that string is malformed

See PMS authors discussing that very issue: https://bugs.gentoo.org/show_bug.cgi?id=489458

quoting Ulrich Müller: 'Maybe we should start with documenting "prefer leftmost" in PMS.'

It has also been discussed on the MLs several times. I can't be bothered to search for every link now.

**Comment by qnikst** [comment]
>  And that's often not so easy, since cabal definitions are sometimes incorrect with overly strict upper version bounds.

I hope you know how we deal with those? And again I'd say "incorrect" is not right word here, restrictive approach sets `<(major version that package was tested with+1)`, and this is correct because major version bump allow to change API in any way, so you can't guarantee that your package will work when dep will be updated. There is a process and manual steps that are added in ebuild to fix that, also we but package maintainers to fix that. What else can we do? We can try to suppose cabal files patches, recently added and not widely used feature on hackage, to make things more automated.

> See PMS authors discussing that very issue: https://bugs.gentoo.org/show_bug.cgi?id=489458

I asked about link to PMS, not link to various discussions where there are no total agreement there. You've said deps line is malformed, so I suppose that there is a paragraph in PMS that we have missed when implemented ebuild generation tool.
It's impossible to say something about correctness without relation to some official spec, or mailing list/bug where that is resolved and decision is correctly stated and no objections comes, though we have PMS so ML or bug tracker do not apply here.

**Comment by Heather** [comment]
@trofi I've used to use your system-updating script that you've shared and it doesn't resolve the problem, seems like running it twice it not enough... what about running it 5 times? what do you think :palm_tree:

**Comment by trofi** [comment]
How does it break for you? Do you have a few build.logs for broken packages?

**Comment by Heather** [comment]
@trofi well, there was some haskell package error and re-running it fixed problem so as I said maybe 5 times is better?

**Comment by trofi** [comment]
I'd better try to fix underlying problem :)

**Comment by Heather** [comment]
@trofi automate rebuilding inside package manager or recursive script runner?

**Comment by trofi** [comment]
You say that 2 haskell-updater rebuilds is not enough for you.

It means full dependency chain does not break after first emerge failure. It's unexpected if you are using --keep-going.
First emerge run should update all packages and break the reset of packages which were not scheduled for update by subslot change.

Do you use --complete-graph when running world update?

I'd like to understand more why it happens.

**Comment by Heather** [comment]
@trofi I used to run : https://github.com/Heather/zsh/blob/master/functions.sh#L22-L28

and first time it's failed (due some haskell package) second time everything was fine (something was recompiling)
